### ISSUE TITLE
[prod-preview] Cannot create new Che workspace on when importing codebase

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1789]
Attempts to create new Che workspaces on prod-preview fail - the UI never gets past this point:

![screenshot from 2018-01-05 20-56-01](https://user-images.githubusercontent.com/642621/34635326-d0b664fa-f25b-11e7-9288-57cfcde08edc.png)

**Comment by joshuawilson** [comment]
@dlabrecq @ibuziuk you guys have the most experience with this. What do you think?
cc @ashumilova

**Comment by dlabrecq** [comment]
Seeing the following error in the browser console, which is probably responsible for the page rendering incorrectly. 

"ERROR TypeError: Cannot read property 'running' of null"

I'm also seeing duplicate information in the "Add Codebase" dialog.

![screen shot 2018-01-08 at 9 39 35 am](https://user-images.githubusercontent.com/17481322/34675493-cfec54d2-f457-11e7-9c0f-8a7b812a5b44.png)

To reproduce, I attempted to add an existing repo. Then, I attempted sync a new one. At this point, I cannot close the dialog. However, I suspect this error is related to the 'running' property being null.

**Comment by dlabrecq** [comment]
FYI, I don't see this error on prod.

**Comment by joshuawilson** [comment]
Prod has not been updated, we need a new issue for the duplication of the UI.

**Comment by dlabrecq** [comment]
I believe it's just a symptom of the same issue.

**Comment by ibuziuk** [comment]
@joshuawilson this might also be related to https://github.com/redhat-developer/rh-che/issues/503
need to check with SD team

**Comment by joshuawilson** [comment]
@dlabrecq can you please check again on prod, we fixed what we think is the issue yesterday.

**Comment by dlabrecq** [comment]
I don't see the issue on prod. Although, I encountered a different issue -- not able to open any workspaces.

I successfully added a new codebase via the dialog. Next, I created a workspace. I'm just not able to open any workspaces -- new or existing. 

I don't see any errors in the browser console. I also tried resetting my user environment.

**Comment by joshuawilson** [comment]
Prod has not been updated yet. Do you see this on prod-preview?

**Comment by ldimaggi** [comment]
I was just able to create and open a new workspace on prod-preview. Looking on prod now.

**Comment by dlabrecq** [comment]
Ok, you said prod above. I don't see the issue with the codebases dialog, but the newly added codebase isn't displayed. I also still see the same errors in the page.

![screen shot 2018-01-09 at 9 38 11 am](https://user-images.githubusercontent.com/17481322/34726082-fa6a5172-f520-11e7-9a3e-64148b3fa73f.png)

**Comment by joshuawilson** [comment]
oops, I meant prod-preview. sorry

**Comment by ibuziuk** [comment]
@ldimaggi are you able to create workspace on prod-preview via dashboard ?

**Comment by ldimaggi** [comment]
On prod-preview, after an env reset, I was able to create a new quickstart, and create a new workspace from the codebase created when the quickstart was created:

![screenshot 91](https://user-images.githubusercontent.com/642621/34738245-6cc89786-f546-11e7-96b2-41cf1c3fdcb4.png)

However, I was not able to create a new workspace after importing a codespace from a repo that was created by creating a quickstart (Vert.x HTTP) earlier in the day - https://github.com/ldimaggi/testjanuary8001

![screenshot 92](https://user-images.githubusercontent.com/642621/34738325-aa3474dc-f546-11e7-915d-5bfa575efda2.png)

**Comment by ibuziuk** [comment]
@ldimaggi I can not reproduce this issue. Can we close or you still facing it ?

**Comment by ibuziuk** [comment]
@ldimaggi closing. feel free to reopen
