### ISSUE TITLE
jenkins.http’s server IP address could not be found.

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4598]
##### Issue Overview

When user navigates to http://jenkins.openshift.io, he sees error page instead of Jenkins UI

##### Expected Behaviour

Jenkins UI is displayed

##### Current Behaviour

Error message
![05-04-jenkins-direct-log](https://user-images.githubusercontent.com/445100/49212684-ea9a8400-f3c2-11e8-8a50-46a9984993cc.png)

##### Steps To Reproduce

1. create a space, create a new app, wait for pipeline to start (might not be necessary)
2. open new tab and open http://jenkins.openshift.io

##### Additional Information

We saw it twice on us-east-1a-beta

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1634/ Nov 28, 2018 4:35:00 PM UTC
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1635/ Nov 28, 2018 6:35:00 PM UTC

We saw similar bug for `api.openshift.io`:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-logintest-us-east-2-released/14962/01-01-afterEach.png Nov 8, 2018 4:28:00 AM UTC
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-logintest-us-east-2a-released/14953/01-01-afterEach.png Nov 8, 2018 4:32:00 AM UTC

**Comment by ppitonak** [comment]
Happened again yesterday, again on us-east-1a with the same account. 

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1647/ Nov 29, 2018 6:35:00 PM

Out of 22 runs, 3 failed with this error. The job runs every 2 hours.

**Comment by ljelinkova** [comment]
I've seen this error on all clusters 1-2 times during weekend, for example:

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1683/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/1159/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/1152/console

There is one thing commong  in oc logs 
```
oc get all
NAME                   READY     STATUS             RESTARTS   AGE
pod/jenkins-1-deploy   0/1       DeadlineExceeded   0          3h
```

Usually, there are no events in the log, maybe because the jobs run only every 4 hours. However, in one job, I've seen quite a lot of log events like this:

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1683/oc-jenkins-logs.txt
```
 Error creating: pods "jenkins-1-j5j6z" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
```

**Comment by ljelinkova** [comment]
This issue still occurs and affects the E2E tests so I'd also like to see some suggestions what we could do about it.

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1169/console

**Comment by ljelinkova** [comment]
@chmouel @stevengutz @ldimaggi

**Comment by ljelinkova** [comment]
This log looks also interesting
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1724/oc-jenkins-logs.txt

Extract:
```
oc get all
NAME                  READY     STATUS        RESTARTS   AGE
pod/jenkins-1-xz7b7   0/1       Terminating   0          1m
.......
kubelet, ip-172-21-55-225.ec2.internal   Killing container with id docker://jenkins:Need to kill Pod
1m          1m           1         jenkins-1-xz7b7.156da5ae712564e6    Pod                                                   Normal    Scheduled                     default-scheduler                        Successfully assigned osio-ci-e2e-002-jenkins/jenkins-1-xz7b7 to ip-172-21-50-152.ec2.internal
1m          1m           1         jenkins-1.156da5ae6ef05c05          ReplicationController                                 Normal    SuccessfulCreate              replication-controller                   Created pod: jenkins-1-xz7b7
1m          1m           1         jenkins-1.156da5ae77087b9d          ReplicationController                                 Normal    SuccessfulDelete              replication-controller                   Deleted pod: jenkins-1-xz7b7
1m          22m          2         jenkins.156da48c68a94215            DeploymentConfig                                      Normal    ReplicationControllerScaled   deploymentconfig-controller              Scaled replication controller "jenkins-1" from 1 to 0
1m          1m           1         jenkins-1.156da5aea63ff670          ReplicationController                                 Warning   FailedCreate                  replication-controller                   Error creating: pods "jenkins-1-r9xt7" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
```

**Comment by ljelinkova** [comment]
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1723/oc-jenkins-logs.txt

**Comment by ljelinkova** [comment]
@piyush-garg The number of failed e2e tests is increasing so give it a high priority please.

**Comment by ppitonak** [comment]
Happened twice in last 40 minutes:
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/4272/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/1181/console

Jenkins seems to unidle properly and start the job:
![osio_ip_1](https://user-images.githubusercontent.com/445100/49594811-f368f800-f976-11e8-8d6b-e06b255a4ce8.png)
But failed to promote the builld:
![osio_ip_2](https://user-images.githubusercontent.com/445100/49594831-fe238d00-f976-11e8-82c3-ba6bcbf5c890.png)
And accessing the Jenkins UI directly resulted in what is this issue about:
![osio_ip_3](https://user-images.githubusercontent.com/445100/49594873-109dc680-f977-11e8-8432-b9859a699475.png)

**Comment by ppitonak** [comment]
Another failure, the same story. Three successful runs before this one so probably not caused by something broken in previous run.
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4274/

**Comment by ppitonak** [comment]
I have more information about what is going on.

* Dec 6, 2018 14:40:00 [build 4273](https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4273/) is started and succeeds, account is reset, nothing unusual in logs
* Dec 6, 2018 15:40:00 [build 4274](https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4274/) is started
* Dec 6, 2018 15:43:56 new space and project is created and pipeline starts
* Dec 6, 2018 15:45:23 e2e test opens pipelines page in OSIO
* Dec 6, 2018 15:53:06 Jenkins pod log shows the stacktrace like in my previous comment - `WARNING: Computer.threadPoolForRemoting [#34] for jenkins-slave-fzpvb-tvc99 terminated`
* Dec 6, 2018 15:53:23.458 pipeline stops on promote stage, e2e test clicks on "Input required" button
* Dec 6, 2018 15:53:23.616 first of many similar errors in browser console `SEVERE https://jenkins.api.prod-preview.openshift.io/api/jenkins/start - Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
* Dec 6, 2018 16:03:23 e2e test timeout - "Promote" button is not clickable
* Dec 6, 2018 16:03:24 e2e test navigates to Jenkins log directly by URL - results in what is reported in this issue (Chrome error ERR_NAME_NOT_RESOLVED)
* Dec 6, 2018 16:03:28 e2e test gathers various logs - nothing unusual in last 15 minutes, Jenkins pod looks OK `pod/jenkins-1-q9gfr                       1/1       Running     0          1h`
* Dec 6, 2018 16:04:01 e2e test **successfully resets** the account

Then https://github.com/openshiftio/openshift.io/issues/3802 goes on stage.
* Dec 6, 2018 16:40:00 [build 4275](https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4275/) is started, fails with **unrelated** issue
* Dec 6, 2018 17:40:00 [build 4276](https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4276/) is started
* Dec 6, 2018 18:05:00 "View log" link on pipeline page is still not available after 21 minutes
* Dec 6, 2018 18:05:00 e2e test navigates to Jenkins log directly by URL - results in what is reported in this issue (Chrome error ERR_NAME_NOT_RESOLVED)
* Dec 6, 2018 18:05:11 e2e test gathers various logs - nothing unusual in last 15 minutes, *Jenkins pod has been live for 3 hours*  `pod/jenkins-1-q9gfr                       1/1       Running     0          3h`
* Dec 6, 2018 18:05:36  e2e test **successfully resets** the account

* fast-forward in time
* Dec 7, 2018 9:40:00 [build 4292](https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4292/) is started
* the same scenario as in build 4276
* Dec 7, 2018 9:54:15 e2e test gathers various logs - nothing unusual in last 15 minutes, *Jenkins pod has been live for 19 hours* `pod/jenkins-1-q9gfr                       1/1       Running     0          19h

result: 
* the account is completely unusable
* user needs to go to OpenShift console and manually delete all pipelines
* (maybe not necessary) reset account

**Comment by ppitonak** [comment]
When I click the " See additional details in jenkins", I see the following error in browser instead of Jenkins UI.

![osio_promote2](https://user-images.githubusercontent.com/445100/49646809-97f34480-fa20-11e8-8d1c-db64f2fbc536.png)

```
{"Errors":[{"code":"500","detail":"Error when starting Jenkins: 2: openshift client error: got status 401 Unauthorized (401) from https://api.starter-us-east-2a.openshift.com/oapi/v1/namespaces/ppitonak-preview-jenkins/deploymentconfigs/jenkins"}]}
```

**Comment by hrishin** [comment]
@ppitonak from where we are seeing the following log?

```
{"Errors":[{"code":"500","detail":"Error when starting Jenkins: 2: openshift client error: got status 401 Unauthorized (401) from https://api.starter-us-east-2a.openshift.com/oapi/v1/namespaces/ppitonak-preview-jenkins/deploymentconfigs/jenkins"}]}
```

**Comment by hrishin** [comment]
@ppitonak yeah, can see now with prod-preview Jenkins.

**Comment by alexeykazakov** [comment]
The token was updated. Should be fixed by now. Please reopen if it's still not working for you.

**Comment by ljelinkova** [comment]
Reopening because the fix did not work and it may not be the root cause of this issue.

**Comment by hrishin** [comment]
@ljelinkova Is it still happening on prod-preview?

I can access the Jenkins now
![image](https://user-images.githubusercontent.com/28615674/49726673-8d40e580-fc94-11e8-832f-aaefc5a68b92.png)

**Comment by chmouel** [comment]
The issue is still that we are getting an invalid token for free-stg : 

We (idler) do get the clusters from auth with the `/api/clusters`  rest path,

We get the token on prodpreview for two clusters, `free-stg` and `east-2a`

Using manually the token provided by auth to east-2a work : 



```bash
 % oc login https://api.starter-us-east-2a.openshift.com/ --token=XXXXX                                                                                       
Logged into "https://api.starter-us-east-2a.openshift.com:443" as "devtools-sre" using the token provided.

You have access to 9120 projects, the list has been suppressed. You can list all projects with 'oc projects'
```

The token for stg is invalid : 


```bash
chmouel@TheBatman ~/GIT/go/src/github.com/fabric8-services/fabric8-jenkins-idler
 % oc login https://api.free-stg.openshift.com/ --token=XXXX
error: The token provided is invalid or expired.

```
so we really need to get a proper token to stg to work,

having said that we should gracefully handle those in idler instead of trying billions times and then running out of memory in the pods, I have logged this issue here to track it : 

https://github.com/openshiftio/openshift.io/issues/4628

**Comment by piyush-garg** [comment]
@ppitonak @ljelinkova Can you please check if the issue has been resolved now? Thanks

**Comment by ppitonak** [comment]
@piyush-garg we are monitoring it closely but it's too soon to judge. Let's give it couple of hours before closing this issue.

**Comment by piyush-garg** [comment]
Thanks, @ppitonak No problem. Just from the last run seems like it is fixed. But close it whenever you are sure about it. Thanks a lot.

**Comment by ppitonak** [comment]
This issue has **NOT** been caused by expired token. We have new occurences:

https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/4372/console
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/4377/console
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4373/console

**Comment by ljelinkova** [comment]
I think that the problem with expired token was not the root cause of this issue, because we are back to Deadline Exceeded status of Jenkins deploy pod. 

These are some of the jobs that failed recently:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1784/oc-jenkins-logs.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1208/oc-jenkins-logs.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1206/oc-jenkins-logs.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1206/oc-jenkins-logs.txt

**Comment by ljelinkova** [comment]
The same in production.

**Comment by chmouel** [comment]
Do you have the link to the openshift logs?

I do have some issue currently on prod with gluster  timing out: 

```
compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
45s         45s          1         jenkins-5-w4p6m.156f3e3c44242486   Pod                                 Warning   FailedMount                   kubelet, ip-172-31-66-195.us-east-2.compute.internal   Unable to mount volumes for pod "jenkins-5-w4p6m_cboudjna-jenkins(6ea9ed2e-fd29-11e8-a5d6-02d7377a4b17)": timeout expired waiting for volumes to attach or mount for pod "cboudjna-jenkins"/"jenkins-5-w4p6m". list of unmounted volumes=[jenkins-home jenkins-config jenkins-token-lbwxh]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-lbwxh]
34s         34s          1         jenkins-5-xnbjf.156f3e3eaeaa0631   Pod                                 Warning   FailedMount                   kubelet, ip-172-31-66-159.us-east-2.compute.internal   Unable to mount volumes for pod "jenkins-5-xnbjf_cboudjna-jenkins(74ce6aff-fd29-11e8-a5d6-02d7377a4b17)": timeout expired waiting for volumes to attach or mount for pod "cboudjna-jenkins"/"jenkins-5-xnbjf". list of unmounted volumes=[jenkins-home jenkins-config jenkins-token-lbwxh]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-lbwxh]
```

**Comment by chmouel** [comment]
if that's the [log](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4373/oc-jenkins-logs.txt), this seems to correlate although the error seems different: 


```log
3m          58m          24950     jenkins-1-hrm5s.156f0a4d8afbbfd4                       Pod                                                              Warning   FailedScheduling    default-scheduler                                      persistentvolumeclaim "jenkins-home" not found
```

Can you show me where is the output of  `oc logs dc/jenkins` please, I'd like to know why readiness probe failed,

**Comment by ljelinkova** [comment]
The deployment config section starts with
```
---------- Jenkins deployment config ---------------
oc get -o yaml dc/jenkins
```

If you want us to add any other command to the script, just specify what shall we add.

**Comment by chmouel** [comment]
@ljelinkova thanks, can you please get us the output of : 

(in jenkins namespace)

> oc  logs dc/jenkins

> oc get ev 

that would be much helpful to debug those,

**Comment by ljelinkova** [comment]
We do have 
```
---------- Get events ---------------
oc get events --sort-by='.lastTimestamp'
```
and I'll add `oc logs dc/jenkins`

**Comment by ppitonak** [comment]
@chmouel 
> `oc logs dc/jenkins`
how is this different from `oc logs jenkins-1-somehash`?

**Comment by chmouel** [comment]
okay right we have all the information, so definitively the issue is with : 

```
3m          58m          24950     jenkins-1-hrm5s.156f0a4d8afbbfd4                       Pod                                                              Warning   FailedScheduling    default-scheduler                                      persistentvolumeclaim "jenkins-home" not found
```

I think we saw that error before? 

you (@ppitonak or someone else chatted to @sthaha  about it, when `jenkins-home` don't get created,  it means  the tenant creation or recreation hasn't been done properly and the volume is not there,

Somehow there is an error hapenning earlier (at tenant creation) where fabric8-tenant fails,

@alexeykazakov @sbose78 do you know how that flow is working ? fabric8-tenant should report somewhere when it cannot instantiate a resource ? My bet is on a gluster timeout not handled properly in fabric8-tenant,

**Comment by chmouel** [comment]
(and as well with those sev1 issues there is multiple issues in a catch all one)

**Comment by chmouel** [comment]
I believe it's then related : https://github.com/openshiftio/openshift.io/issues/4121

**Comment by alexeykazakov** [comment]
cc: @MatousJobanek

**Comment by MatousJobanek** [comment]
I was trying o find anything relevant in the tenant logs - related to this issue - unfortunately, I haven't found anything (which doesn't mean that there is nothing :-))

> there is a race somewhere in the test that makes the jenkins home not creating,

if the Reset, Clean & Apply is fast enough and OpenShift slow enough, then it can happen that some objects are still present in OS while creation of the new ones with the same name is requested. 
I see two options for fixing this:
* try to detect that there is such an object that is still in `terminating` state and wait until it is completely gone. However, I'm afraid that in case of PVC it can happen that it seems to be removed, but when tenant tries to create a new one with the same name, then it fails anyway
* if there is either a conflict or 403 returned from OS for PVC in `mjobanek-jenkins` namespace (or any other one), then tenant should try to create new namespaces with different base name: `mjobanek1-jenkins`

as the safest way seems to be the second solution. Currently, I'm validating this against local minishift instance.

**Comment by Preeticp** [comment]
I am also facing the same issue as mentioned above, not able to mount volume. Attaching screenshot

![jenkins](https://user-images.githubusercontent.com/16647625/49932472-1ce1d080-feef-11e8-9b01-209811748575.png)

**Comment by chmouel** [comment]
@Preeticp that's another issue, this is not an issue where the volume wasn't created but where it's timing out mounting out from gluster, from my experience the dc would come up after a while or we need to wait for gluster upgade to fix this (I am not sure where we have a issue for the upgrade)

**Comment by chmouel** [comment]
@MatousJobanek 

I have seen this script floating around https://github.com/sborenst/ansible_agnostic_deployer/blob/development/ansible/configs/ocp-workshop/files/wack_terminating_project.sh not sure if this  call : 



```bash
curl -s -k -H "Content-Type: application/json" -X PUT --data-binary @$tmp http://127.0.0.1:28001/api/v1/namespaces/$project/finalize > /dev/null
```

could be useful to force terminate, 

for 

> if there is either a conflict or 403 returned from OS for PVC in mjobanek-jenkins namespace (or any other one), then tenant should try to create new namespaces with different base name: mjobanek1-jenkins

I am not sure i understand you are suggesting, would that break some associations ?

**Comment by MatousJobanek** [comment]
> I have seen this script floating around https://github.com/sborenst/ansible_agnostic_deployer/blob/development/ansible/configs/ocp-workshop/files/wack_terminating_project.sh not sure if this call can be useful for us when resetting a tenant:

I'm not sure if force-terminating and expecting that the original PVC should be immediately correctly removed is the best solution.

> I am not sure i understand you are suggesting, would that break some associations ?

it shouldn't break anything. we are already using this [logic](https://github.com/fabric8-services/fabric8-tenant/pull/675) for [cases](https://github.com/fabric8-services/fabric8-tenant/issues/674) when there are two users with the same name. TLDR explanation would be:
Currently, the namespace names are constructed by getting the first part of the OS username (for `mjobanek@redhat.com` it is `mjobanek`) and joining with the namespace suffix (for jenkins it is `mjobanek-jenkins`). If there was another account `mjobanek@ibm.com` then it would conflict with the first one so to solve it we change the base-name for namespaces to `mjobanek2` which means `mjobanek2-jenkins` for the jenkins namespace. This is only internal linking and no other component/service should be affected by that.
Our case could be solved using the same logic - when the creation of the namespaces fails because of either 409 or 403, then tenant service could increment the suffix of the base-name (`mjobanek3`) and try to create new namespaces with it.

**Comment by chmouel** [comment]
@MatousJobanek sounds good then thanks for taking the time to describe how it works, I think that looks good then!

> I'm not sure if force-terminating and expecting that the original PVC should be immediately correctly removed is the best solution.

I think the state terminating mean the volume drive is 'recycling' the gluster volumes and it is stuck into it at that time, perhaps @jfchevrette or @pbergene can give us some advice here.

**Comment by bmicklea** [comment]
What's the latest status on this?

**Comment by piyush-garg** [comment]
@ljelinkova @ppitonak Any updates about how the tests are performing now?

**Comment by ppitonak** [comment]
@piyush-garg observed twice in last 24 hours but there is a problem in Launcher at the moment so many builds didn't get that far.

https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/4548/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1248/console

**Comment by chmouel** [comment]
I have unassigned myself, this is not something we can solve from the build side, as stated before this is or the test or fabric8-tenant that can fix this,

**Comment by bmicklea** [comment]
`SEV1` label downgraded during the IC today due to the fact that users shouldn't be doing reset environment ever, let alone frequently. We can't remove it from the E2E tests though because there's nothing that can replace it as a method to provide a clean environment for testing.

Separately the docs team needs to ensure that the onboarding doc sent to users does not reference the reset environment command: https://github.com/openshiftio/openshift.io/issues/4656

**Comment by piyush-garg** [comment]
As mentioned in previous comments and also explained, this is reset environment and platform team is taking care/looking at it. I will add the platform team label and remove build team label. If build team needs to do something regarding this, please assign back. Thanks

**Comment by MatousJobanek** [comment]
Just a small update - the "fix" (from the tenant point of view) is done https://github.com/fabric8-services/fabric8-tenant/pull/714 - now I'm just waiting till the [quay database](http://status.quay.io/) is fixed, so I can merge it and deploy it to prod-preview.

**Comment by alexeykazakov** [comment]
The tenant master build is green again and the fix has been deployed to prod-preview.

**Comment by alexeykazakov** [comment]
Should be fixed in https://github.com/fabric8-services/fabric8-tenant/pull/714 (in prod-preview now).

**Comment by ppitonak** [comment]
We cannot judge if the fix helped because of https://github.com/openshiftio/openshift.io/issues/4670

**Comment by ljelinkova** [comment]
https://github.com/openshiftio/openshift.io/issues/4670 is resolved now. 

I can see some failed jobs on prod-preview caused by Jenkins, for example. 

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4957/oc-jenkins-logs.txt

However, this could be also caused by https://github.com/openshiftio/openshift.io/issues/4668 . Could anybody have a look at https://github.com/openshiftio/openshift.io/issues/4668 so that it can be resolved and we can focus on this issue?

**Comment by ljelinkova** [comment]
The #4670 is resolved and it seems that the fix on prod-prev helped to lower the number of occurrences. However, it still happens. 

These are the last logs

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/5247/oc-jenkins-logs.txt

I can see in the logs that readiness probe failed
```
Readiness probe failed: Get http://10.130.24.191:8080/login: dial tcp 10.130.24.191:8080: connect: connection refused
```

And then the quota limit
```
Error creating: pods "jenkins-1-pbmt7" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
```

**Comment by ppitonak** [comment]
I would just add that there is another type of suspicious OpenShift events:
```
9m          9m           1         jenkins-slave-6x3x2-1g0z0.157a94c2abcd6233             Pod                                                              Warning   Evicted                       kubelet, ip-172-21-52-86.ec2.internal   The node was low on resource: ephemeral-storage. Container jnlp was using 684Ki, which exceeds its request of 0. Container maven was using 636Ki, which exceeds its request of 0. 
```
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1431/oc-jenkins-logs.txt

@MatousJobanek @alexeykazakov who is working on this? Nobody is assigned to this issue.

**Comment by MatousJobanek** [comment]
Well, we (platform team) were asked to try to resolve this issue by fixing the [missing PVC one](https://github.com/openshiftio/openshift.io/issues/4121). That issue has been fixed (or at least it's [not been observed](https://github.com/openshiftio/openshift.io/issues/4121#issuecomment-455111941) for a long time). 

These "new" failures and suspicious events reported by @ppitonak as well as by @ljelinkova are of different kind. Anyone from the Build team could say what the cause is @piyush-garg @chmouel. If there is anything we could help with, please just let me know. 

If there is anything I'm missing or I'm wrong about with my assumption, then I just probably need additional clarification

**Comment by ppitonak** [comment]
@chmouel can you do something about failing readiness probe?

**Comment by chmouel** [comment]
I think it's better to fail fast than trying to just wait more, the increase startup time with storage should not be greater than a second, 

in the case of that other bug, this was because there was a node eviction going on (out of resources) and just waiting more is not fixing it, 

we could potentially handle this in the pipeline to detect errors and retry the pipeline but the detection is going to be fragile and may not help much, 

can I respectively ask (again) to log a new issue instead of dumping everything on this one or just rename this issue to something like "OpenShift uber tracking instability issue"

**Comment by ppitonak** [comment]
@chmouel I am happy to report a new issue when there is a new issue but from my end point of view, it's still the same symptom which could have one or more root causes.

The two links in issue description contain these clues:
* jenkins-home PVC problem
* readiness probe failed
* exceeded quota

Later we identified the problem with evicted pods and I agree with you that it's unrelated/not in our hands.

What should I report in a new issue?

**Comment by ljelinkova** [comment]
The e2e tests failed on `persistentvolumeclaim "jenkins-home" not found` both on prod and prod-prev. 

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2274/oc-jenkins-logs.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/5365/oc-jenkins-logs.txt

**Comment by chmouel** [comment]
This seems to be an error where the pod didn't get out of terminated and get stuck : 

```bash
oc get pods --field-selector=status.phase=Running -o name | grep -v 'slave|deploy' | grep -m1 jenkins
oc logs pod/jenkins-1-hkf75
Error from server (BadRequest): container "jenkins" in pod "jenkins-1-hkf75" is terminated
```

**Comment by ppitonak** [comment]
What is the progress of this issue? It's still appearing, e.g. http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1509/
