### ISSUE TITLE
Filter "Repository name pattern" is not obvious

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#543]
Having to click in the filter button in the combo is not obvious. The filter should always be enabled.

![screenshot 2017-08-10 09 23 14](https://user-images.githubusercontent.com/30131/29172344-b1228a60-7dad-11e7-81ef-8e358201522d.png)

**Comment by joshuawilson** [comment]
The wizard is under design. The new version should fix this.

**Comment by corinnekrych** [comment]
@catrobson do we have any widget in patternfly-ng that could help?

**Comment by catrobson** [comment]
Does this field still exist?  What does it do so I can better identify the right widget?

**Comment by rafabene** [comment]
@catrobson Yes. The field still exists and it still hard to understand the "filter" usage.

**Comment by corinnekrych** [comment]
@catrobson indeed we reuse the same multi-slelect filter list as defined by Mitch. I also don't find it intuitive. For exemple, once you have filter and selected an item and you want to remove it, you can not edit the input to remove a selection, you have to either browse the whole list and remove it from checkbox or filter again to find it and remove it from the.
![wizard_filter_multi_select](https://user-images.githubusercontent.com/1395710/31651758-2dd2a014-b31d-11e7-9e8c-182e35777c03.gif)

**Comment by joshuawilson** [comment]
@catrobson is this something that is still under design?

**Comment by catrobson** [comment]
Created UXD issue to identify or create better widget/experience for this.  https://github.com/fabric8-ui/fabric8-ux/issues/759

**Comment by jaseemabid** [comment]
xref https://github.com/openshiftio/openshift.io/issues/1421

**Comment by qodfathr** [comment]
I'm going to re-type this as a bug.

**Comment by joshuawilson** [comment]
@catrobson is this in the new designs?

**Comment by catrobson** [comment]
Yes, the designs here change this to a searchable list pattern: 
https://redhat.invisionapp.com/share/EGF2SMJQ3

**Comment by joshuawilson** [comment]
Closing as it is being redesigned.

**Comment by ppalaga** [comment]
Results of the redesign still not visible live.

> @catrobson  https://redhat.invisionapp.com/share/EGF2SMJQ3

Could please the selection of github repo be search/selected through one input field? Pasting/typing myaccount/myrepo is much faster than typing myaccount, waiting for the list, then searching through the list and selecting myrepo. Or even pasing https://github.com/myaccount/myrepo (and variants of) should work too.
